version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "YOUR_STACK_NAME"
s3_bucket = ""
s3_prefix = "YOUR_S3_PREFIX"
region = "us-east-1"
confirm_changeset = false
disable_rollback = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
