AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ServerlasticFunction

Resources:
  ServerlasticFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: node_on_http_server_function
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: Any
        All:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: Any
      FunctionUrlConfig:
        AuthType: NONE
      Timeout: 3
      MemorySize: 128
      ReservedConcurrentExecutions: 1

    Metadata:
      DockerContext: ../
      Dockerfile: Dockerfile.sam
      DockerTag: latest
      DockerBuildArgs:
        ARG_SERVER_IMAGE: node_on_http_server-app

Outputs:
  ServerlasticFunctionHttpApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
  ServerlasticFunction:
    Description: AWS::Lambda::Function
    Value: !GetAtt ServerlasticFunction.Arn
  ServerlasticFunctionRole:
    Description: AWS::IAM::Role
    Value: !GetAtt ServerlasticFunctionRole.Arn
  ServerlasticFunctionUrl:
    Description: AWS::Lambda::Url
    Value: !GetAtt ServerlasticFunctionUrl.FunctionUrl
  ServerlasticFunctionUrlPublicPermissions:
    Description: AWS::Lambda::Permission
    Value: !Ref ServerlasticFunctionUrlPublicPermissions
