ARG ARG_SERVER_IMAGE
FROM ${ARG_SERVER_IMAGE}:latest

SHELL ["/bin/sh", "-c"]

USER root

# https://docs.aws.amazon.com/lambda/latest/dg/images-create.html
RUN apt update && \
  apt install -y \
  g++ \
  make \
  cmake \
  unzip \
  libcurl4-openssl-dev \
  curl \
  dh-autoreconf \
  python3

ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8

RUN getent passwd '1000' | cut -d: -f1 | { read username; [ -z "$username" ] && exit 0 || deluser --remove-home $username; } && \
  addgroup --gid '1000' user && \
  adduser --disabled-password --gecos '' --uid '1000' --gid '1000' user && \
  passwd -d root && \
  echo 'user ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers && \
  chown user:user -R "/usr/local"

USER user

RUN wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_386.tar.gz -O - |\
  tar xz && mv yq_linux_386 "/usr/local/bin/yq" && \
  sudo apt install -y siege

ARG ARG_RIC_NODE_VERSION
RUN sudo mkdir "/var/ric" && \
  sudo chown user:user "/var/ric" && \
  wget -nv "https://nodejs.org/dist/v14.20.0/node-v14.20.0-linux-x64.tar.gz" && \
  tar -xf "node-v14.20.0-linux-x64.tar.gz" --directory '/var/ric' --strip-components '1' && \
  rm -rf "node-v14.20.0-linux-x64.tar.gz" && \
  /var/ric/bin/npm install -g aws-lambda-ric@2.0.0

RUN sudo mkdir "/var/rapid" && \
  sudo chown user:user "/var/rapid" && \
  curl -Lo "/var/rapid/aws-lambda-rie-x86_64" https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie

COPY --chown=user:user . "/home/user/serverlastic"

RUN cd "/home/user/serverlastic" && \
  chmod +x sam/devops/server/*.sh && \
  ./sam/devops/server/install.sh && \
  /var/ric/bin/npm remove aws-lambda-ric && \
  cd sam && \
    /var/ric/bin/npm install && \
    /var/ric/bin/npm remove aws-lambda-ric && \
    cd ../../ && \
  mv 'serverlastic/sam' 'sam' && \
  rm -rf 'serverlastic/.aws-sam' && \
  rm -rf 'serverlastic/.git' && \
  zip -rm1q 'serverlastic.zip' 'serverlastic'

RUN locale && \
  echo "npx: `npx --version`" && \
  yq --version && \
  siege --version

WORKDIR "/home/user/sam"

ENTRYPOINT ["/var/ric/bin/npx", "/usr/local/bin/aws-lambda-ric"]

CMD ["app/lambda.handler"]

USER root
