version: '3.9'
services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_RUBY_VERSION: 3.1.2
        ARG_NODE_VERSION: 16.16.0
      context: .
    depends_on:
      - postgresql
    working_dir: /home/user/ruby_on_rails
    environment:
      BINDING: 0.0.0.0
      PORT: 3000
      DATABASE_URL: postgres://user:password@postgresql:5432
    extra_hosts:
      - dockerhost:host-gateway
    ports:
      - 3000:3000
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/ruby_on_rails
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  app_local:
  postgresql_data:
